[tool.black]
line-length = 119
target-version = ['py310']

[tool.isort]
profile = "black"

[tool.pylint.'MESSAGES CONTROL']
disable = [
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "duplicate-code",
  "too-few-public-methods",
  "broad-exception-caught",
]

[tool.pylint.'FORMAT']
max-line-length = 119

[tool.flake8]
max-line-length = 119
